version: '3'

services:
  flask_app:
    build: ./app
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.template:ro
      - ./certs:/etc/letsencrypt:ro
    environment:
      - DOMAIN=${DOMAIN:-yourdomain.com}
    command: /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      flask_app:
        condition: service_healthy

  certbot:
    build: ./certbot
    volumes:
      - ./certs:/certs
      - ./certs:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN:-yourdomain.com}
      - EMAIL=${EMAIL:-your@email.com}
    depends_on:
      - nginx

networks:
  default:
    name: foundation_network